### ISSUE TITLE
Storybook display issue

### ISSUE THREAD

**Issue by madeleine-patience** [madeleine-patience/Considerate-Cat-Version-2-With-Next#32]
With Tarot dialog, for some reason in storybook the dialog has a small scroll bar. I can't figure out why.

I tried applying a decorator and adjusting the width of the page. Dialog is fine on site, not sure why storybook is displaying it weird.

![image](https://github.com/user-attachments/assets/b6db7cc7-33a9-46fb-b0ec-e59132b9ab25)

**Comment by arthvadrr** [comment]
Looking into this

**Comment by arthvadrr** [comment]
This bug seems to only happen in certain browsers, such as Chrome (Blink rendering engine). There are conflicting rules preventing exact sizes from being rendered (related to gap and max-height) so the browser is attempting to fit the content, causing an overflow.

The best way to solve this would be to clean up the styles and remove any sizes that will conflict with the rendering engine.

I'll see if I can create a PR that addresses this issue.
